POST  http://localhost:5161/auth/register
Content-Type: application/json

{
    "firstName": "Laughing",
    "lastName": "Thomas",
    "email": "laughing.thomas@laughingkids.me",
    "password": "Password123!"
}
