GET  http://localhost:5161/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjYTBhMjE4OC0xMTc4LTQ0ZjAtOWIyOS0xZTg1OTlkZTQ4ZTMiLCJnaXZlbl9uYW1lIjoiTGF1Z2hpbmciLCJmYW1pbHlfbmFtZSI6IlRob21hcyIsImp0aSI6ImI1OWJmNjYxLTY5MjktNGNjZC1iYjBlLTJmZTA4Mzk5YjUwOSIsImV4cCI6MTY5MTQwMDMyNywiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.eXcuUmdTHeZ9L7DtMwltmSSKY9v9nG4csk48RxRMg7o