GET  http://localhost:5161/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjA1NTk1NC1mZjZlLTRlYTktODYxOS00OTc2N2QxZDg5ZTciLCJnaXZlbl9uYW1lIjoiTGF1Z2hpbmciLCJmYW1pbHlfbmFtZSI6IlRob21hcyIsImp0aSI6IjkyZDA4NjBiLWY4NzYtNDYzZS1hYzE3LTA2YmY0ZDczOWRiMyIsImV4cCI6MTY5MTMwMzY3MCwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.VBN3Wx8e_Nse2ceZnqy6iiR8n0Ry3_viVU4qXFjhwqQ